//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BUYS_MEDICINE_FROM
    {
        public int ID { get; set; }
        public string C_SSN { get; set; }
        public int Pharmacy_ID { get; set; }
        public int Medicine_ID { get; set; }
        public int Buy_amount { get; set; }
        public System.DateTime Transaction_date { get; set; }

        [ForeignKey("C_SSN")] public virtual CUSTOMER CUSTOMER { get; set; }
        [ForeignKey("Medicine_ID")] public virtual MEDICINE MEDICINE { get; set; }
        [ForeignKey("Pharmacy_ID")] public virtual PHARMACY PHARMACY { get; set; }
    }
}
