//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class GETS_MEDICINE_FROM
    {
        public int ID { get; set; }
        public int MC_ID { get; set; }
        public int Pharmacy_ID { get; set; }
        public int Medicine_ID { get; set; }
        public int Buy_amount { get; set; }
        public System.DateTime Transaction_date { get; set; }
    
        [ForeignKey("MC_ID")] public virtual MEDICINE_COMPANY MEDICINE_COMPANY { get; set; }
        [ForeignKey("Pharmacy_ID")] public virtual PHARMACY PHARMACY { get; set; }
    }
}
