//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MEDICINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINE()
        {
            this.BUYS_MEDICINE_FROM = new HashSet<BUYS_MEDICINE_FROM>();
            this.PRESCRIPTIONs = new HashSet<PRESCRIPTION>();
        }
    
        public int ID { get; set; }
        public string MName { get; set; }
        public string MType { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> Price_in_TL { get; set; }
        public Nullable<int> Pharmacy_ID { get; set; }
        public int MC_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYS_MEDICINE_FROM> BUYS_MEDICINE_FROM { get; set; }
        [ForeignKey("MC_ID")] public virtual MEDICINE_COMPANY MEDICINE_COMPANY { get; set; }
        [ForeignKey("Pharmacy_ID")] public virtual PHARMACY PHARMACY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESCRIPTION> PRESCRIPTIONs { get; set; }
    }
}
