//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE_COMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINE_COMPANY()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.GETS_MEDICINE_FROM = new HashSet<GETS_MEDICINE_FROM>();
            this.MEDICINEs = new HashSet<MEDICINE>();
            this.MEDICINE_COMPANY_LOCATIONS = new HashSet<MEDICINE_COMPANY_LOCATIONS>();
        }
    
        public int ID { get; set; }
        public string MCName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETS_MEDICINE_FROM> GETS_MEDICINE_FROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICINE> MEDICINEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICINE_COMPANY_LOCATIONS> MEDICINE_COMPANY_LOCATIONS { get; set; }
    }
}
