//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHARMACY_DATABASEEntities : DbContext
    {
        public PHARMACY_DATABASEEntities()
            : base("name=PHARMACY_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUYS_MEDICINE_FROM> BUYS_MEDICINE_FROM { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<GETS_MEDICINE_FROM> GETS_MEDICINE_FROM { get; set; }
        public virtual DbSet<MEDICINE> MEDICINEs { get; set; }
        public virtual DbSet<MEDICINE_COMPANY> MEDICINE_COMPANY { get; set; }
        public virtual DbSet<MEDICINE_COMPANY_LOCATIONS> MEDICINE_COMPANY_LOCATIONS { get; set; }
        public virtual DbSet<PHARMACIST> PHARMACISTs { get; set; }
        public virtual DbSet<PHARMACY> PHARMACies { get; set; }
        public virtual DbSet<PRESCRIPTION> PRESCRIPTIONs { get; set; }
    }
}
