//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PHARMACIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHARMACIST()
        {
            this.PHARMACIST1 = new HashSet<PHARMACIST>();
        }
    
        [Key] public string SSN { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Salary { get; set; }
        public int Pharmacy_ID { get; set; }
        private string leader_ssn;
        public string Leader_SSN
        {
            get => leader_ssn;
            set { leader_ssn = (string.IsNullOrEmpty(value) || string.IsNullOrWhiteSpace(value)) ? null : value; }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [ForeignKey("Leader_SSN")] public virtual ICollection<PHARMACIST> PHARMACIST1 { get; set; }
        public virtual PHARMACIST PHARMACIST2 { get; set; }
        [ForeignKey("Pharmacy_ID")] public virtual PHARMACY PHARMACY { get; set; }
    }
}
