//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PRESCRIPTION
    {
        public int ID { get; set; }
        public string Hospital_name { get; set; }
        public string Doctor_name { get; set; }
        public string C_SSN { get; set; }
        public Nullable<int> Mecidine_ID { get; set; }

        [ForeignKey("C_SSN")] public virtual CUSTOMER CUSTOMER { get; set; }
        [ForeignKey("Mecidine_ID")] public virtual MEDICINE MEDICINE { get; set; }
    }
}
